name: py310-2023
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - asciitree
  - black
  - colorama
  - colorful
  - configparser
  - control
  - coolprop
  - dataclasses
  - graphviz
  - intervals
  - matplotlib
  - more-itertools
  - mypy
  - nb_conda_kernels
  - nidaqmx-python
  - numpy
  - pandas
  - pdoc3
  - pip
  - pulp
  - pydot
  - pydotplus
  - pydstool
  - pygraphviz
  - pylint
  - pytest
  - python==3.10
  - pyvisa
  - pyvisgraph
  - scipy
  - shapely
  - slycot
  - stopit
  - pip:
    - dwf
    - salabim
