# Conda environment configuration file for virtual environment
# `spyder-nb-2023`, for use in the Digital Exam Environment
#
# conda packages, followed by pip
#
# ```bash
# $ conda env create -f spyder-nb-2023.yml
# ```
#
# update using:
# ```bash
# $ conda env update -f spyder_nb_2023.yml
# ```
#
# Occasional install using pip (notebook)
#
# ```python
# # example: install module pulp here in the notebook ...
# import sys !{sys.executable} -m pip install pulp
# ```
#
# Bart H.M. Gerritsen (EEMCS), version: 2023-1
#
name: spyder-nb-2023
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - colorama
  - dataclasses
  - intervals
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab>=3.5.3
  - matplotlib
  - mypy
  - nb_conda_kernels
  - nose
  - numpy
  - pip
  - pylint
  - pytest
  - python==3.10
  - qtconsole>=5.5
  - scipy
  - spyder-notebook
