name: osx-arm64

on: [push]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          miniforge-version: latest
      - name: Install constructor
        run: |
          conda info
          conda install constructor>=3.12.2
      - name: Build the installer
        env:
          CONDA_CHANNEL_PRIORITY: strict
        run: |
          constructor .
          python pretty_pkg_list.py
          ls -al
      - name: Archive the base package list
        uses: actions/upload-artifact@v4
        with:
          name: tudelft-conda-osx-64-base-pkg-list
          path: pkg-list.base.txt
      - name: Archive the pytorch env package list
        uses: actions/upload-artifact@v4
        with:
          name: tudelft-conda-osx-64-pytorch-pkg-list
          path: pkg-list.pytorch.txt
      - name: Archive the installer
        uses: actions/upload-artifact@v4
        with:
          name: tudelft-conda-osx-arm64-installer
          path: tudelft-conda-v2025.03.dev-MacOSX-arm64.sh
      - name: Archive the installer
        uses: actions/upload-artifact@v4
        with:
          name: tudelft-conda-osx-arm64-pkg-installer
          path: tudelft-conda-v2025.03.dev-MacOSX-arm64.pkg
  install:
    name: Install and test
    runs-on: macos-latest
    needs: build
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tudelft-conda-osx-arm64-installer
      - run: pwd
      - run: ls -al
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          installer-url: file:///Users/runner/work/anaconda-dee-config/anaconda-dee-config/tudelft-conda-v2025.03.dev-MacOSX-arm64.sh
          auto-activate-base: true
          activate-environment: ""
      - name: Test
        run: |
          conda info
          conda config --show-sources
          conda list
          conda run -n base python tests/test_imports.py
          conda run -n base python tests/test_slycot.py
          conda run -n base python tests/test_biogeme.py
          conda run -n pytorch python tests/test_pytorch.py
