name: windows

on: [push]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          miniforge-version: latest
      - name: Conda
        run: |
          conda info
          conda install constructor
          conda list
      - name: Conda
        run: |
          constructor .
          Get-Content .\pkg-list.base.txt

