name: windows

on: [push]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          miniforge-version: latest
      - name: Install constructor
        run: |
          conda info
          conda install constructor
      - name: Build the installer
        run: |
          constructor .
          python pretty_pkg_list.py
          (Get-Item -Path .\tudelft-anaconda-v2024.dev-Windows-x86_64.exe).Length/1MB
      - name: Archive the installer
        uses: actions/upload-artifact@v4
        with:
          name: tudelft-anaconda-installer
          path: tudelft-anaconda-v2024.dev-Windows-x86_64.exe
